name: Build OS image of current rpi-docker

on:
  push:
    branches:
      - rpi-docker

jobs:
  build:

    env:
      REGISTRY: ghcr.io
      IMAGENAME: ${{ github.event.repository.name }}
      TAG: 0.1
      
    runs-on: ubuntu-20.04

    steps:
    - name: Run apt update
      run: sudo apt update

    - name: Install dependencies
      run: sudo apt -y install quilt qemu-user-static debootstrap libarchive-tools jq

    - name: Nuke current Docker installation
      run: |
        sudo systemctl stop docker
        sudo apt-get purge docker-ce docker-ce-cli containerd.io moby-engine moby-cli
        sudo rm -rf /var/lib/docker
    - name: Re-install Docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        docker --version
    - name: Enable experimental features in Docker
      run: |
        sudo rm -rf /etc/docker/daemon.json
        echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
        sudo systemctl restart docker

    - uses: actions/checkout@v2
      name: Check out code
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.20.x
    #- name: Run tests
    #  run:  go test
    - name: Build Nostr-Wallet-Connect Docker Image
      run: |
        cd /home/runner/work/nostr-wallet-connect/nostr-wallet-connect/
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --tag getumbrel/nostr-wallet-connect:0.0.1 \
          --output "type=registry" \
          --push "${IMAGENAME}"
      
        
    #- name: Copy ZIP to current working dir
    #  run: cp nostr-wallet-connect/deploy/*.zip ./

    - name: Uploading artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ${{ env.IMAGE_NAME }}.zip
        name: ${{ env.IMAGE_NAME }}.zip
