name: Docker build & push
on:
  push:
  release:
    types: [published]
jobs:
  buildx:
    env:
      REGISTRY: ghcr.io
      IMAGENAME: ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.20.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run:  go test
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      id: build
      with:
        image: ${{ env.IMAGENAME }}
        registry: ${{ env.REGISTRY }}
        platforms: linux/amd64,linux/arm64
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
